# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ebe88612996ea2ac3503bb0aafaf3f71c993c306ce52525007eee0b4f6784ab8b202cd8ce23e25fa4704b24cc70460c387be851aa4ca733d8fc1beb54ffb018

test:
  secret_key_base: 4b8d0c08e6d7b261949a2dfb04a39368baae818f6d54ab9226d32180d875ea0baf3fbcc4bf08796455282ec2cf36cdaa98fc4bf63750fb01d542dd2e48d528e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
